#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          homesystem
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Should-Start:      $named
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage homesystem
### END INIT INFO


case "$1" in 
    start)
        echo "Starting homesystem"
        sudo /home/pi/home-system-node/startup.sh        
        ;;
    stop)
        echo "Stopping homesystem"
        sudo killall homesystem
        ;;
    *)
        echo "Usage: /etc/init.d/homesystem start|stop"
        exit 1
        ;;
esac
exit $?

