#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          rfsniffer
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Should-Start:      $named
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage rfsniffer
### END INIT INFO


case "$1" in 
    start)
        echo "Starting rfsniffer"
        sudo /home/pi/433Utils/RPi_utils/startup.sh        
        ;;
    stop)
        echo "Stopping rfsniffer"
        sudo killall rfsniffer
        ;;
    *)
        echo "Usage: /etc/init.d/rfsniffer start|stop"
        exit 1
        ;;
esac
exit $?

